### ISSUE TITLE
Error when Nesting less files

### ISSUE THREAD

**Issue by jorgepedret** [sintaxi/harp#2]
I have two files:
bar.less

``` css
body {
  background: #000;
}
```

foo.less

``` css
@import bar.less
body {
  border: red solid 10px;
}
```

Expected behaviour: The body will render a black background with a 10px red border

Current behaviour: The CLI breaks outputting the following error:

```
/usr/local/lib/node_modules/harp/node_modules/less/lib/less/parser.js:418
                        else                                  throw new(LessEr
                                                                    ^
[object Object]
```
