### ISSUE TITLE
Special characters interfere with CSS

### ISSUE THREAD

**Issue by kennethormandy** [sintaxi/harp#40]
Using special characters in a LESS or Stylus file causes the end of the CSS file to get cut off a few characters early.

**Input**

``` sass
q
    quotes: "“" "”" "‘" "’"

body
    background: #FF00AA
```

**Expected Output**

``` css
q {
    quotes: "“" "”" "‘" "’";
}
body {
    background: #FF00AA;
}
```

**Actual Output**

``` css
q {
  quotes: "“" "”" "‘" "’";
}
body {
  background:
```
