### ISSUE TITLE
Stylus output is compressed differently

### ISSUE THREAD

**Issue by kennethormandy** [sintaxi/harp#41]
The following could be either Stylus or LESS:

``` less
body {

  background: #f0f;

}

div {

  background: #f00;

}
```

If it’s LESS, it will be compiled as:

``` css
body {background: #f0f;}
div {background: #f00;}
```

If it’s Stylus, it is compressed, but not quite as much:

``` css
body {
  background: #f0f;
}
div {
  background: #f00;
}
```

Unless this is something being specified by the preprocessor, I would have expected the compression to happen way for both.
