### ISSUE TITLE
Enable turning off autoprefixer

### ISSUE THREAD

**Issue by m90** [sintaxi/harp#417]
While the autoprefixer definitely is great, it is a little too upfront for some of us in its assumptions regarding what to prefix / not to prefix.

The case I ran into right now was that it will turn this:

```less
.box(){
-webkit-box-sizing: border-box;
-moz-box-sizing: border-box;
box-sizing: border-box;
}
.foo-bar{
.box();
}
```
into
```css
.foo-bar{box-sizing:border-box}
```
While that's all fine in an evergreen world I do have clients using Android 2 browsers or some weird nightly build version of Firefox 17 that won't go away because the sysadmin says it won't. Meaning I do need the prefixed properties as well.

While that is my problem I think it would be nice to be enable people to turn off "modern" features like that.
