### ISSUE TITLE
Nicer CSS error messages

### ISSUE THREAD

**Issue by jorgepedret** [sintaxi/harp#9]
When there's something broken in my LESS file, it'd be nice if instead of giving me back an html/text response, I get back the error injected in CSS like this:

``` css
body:before {
  display: block;
  content: "There was an error in your CSS, fix it!";
  border: #EED3D7 solid 1px;
  border-radius: 5px;
  color: #B94A48;
  background-color: #F2DEDE;
  padding: 10px;
  margin: 20px;
  font-family: monospace;
  font-size: 14px;
}
```
